### ISSUE TITLE
关于yolox的构造函数

### ISSUE THREAD

**Issue by Andrawzyf** [hpc203/bytetrack-opencv-onnxruntime#1]
up主你好，我看到你代码里有几行不是特别明白，yolox::yolox()
 string model_path = "/home/ByteTrack/byte_tracker/model/bytetrack_s.onnx";
为啥YOLOx的构造函数里面读取的是bytetrack_s.onnx的模型？其实我可以理解为是对跟踪模型的读取，请问放在这里面有特别的含义么？

**Comment by hpc203** [comment]
> up主你好，我看到你代码里有几行不是特别明白，yolox::yolox() string model_path = "/home/ByteTrack/byte_tracker/model/bytetrack_s.onnx"; 为啥YOLOx的构造函数里面读取的是bytetrack_s.onnx的模型？其实我可以理解为是对跟踪模型的读取，请问放在这里面有特别的含义么？

这个是yoloxs的模型文件的，bytetrack是一个目标跟踪器，它是没有采用深度学习算法实现跟踪的，因此也就没有模型文件

**Comment by Andrawzyf** [comment]
> > up主你好，我看到你代码里有几行不是特别明白，yolox::yolox() string model_path = "/home/ByteTrack/byte_tracker/model/bytetrack_s.onnx"; 为啥YOLOx的构造函数里面读取的是bytetrack_s.onnx的模型？其实我可以理解为是对跟踪模型的读取，请问放在这里面有特别的含义么？
> 
> 这个是yoloxs的模型文件的，bytetrack是一个目标跟踪器，它是没有采用深度学习算法实现跟踪的，因此也就没有模型文件

细看了一下，是这样子。。。。理解错了，感谢回答，问题关闭。。
